Something crashed at <%= @exception.created_at %>: <%= @exception.message %>

REQUEST:
<%= @exception.request %>

BACKTRACE:
<%= @exception.backtrace %>

